// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiserver.Data;

#nullable disable

namespace apiserver.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("apiserver.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "This is placeholder text numer 1 it may be changed later.",
                            Title = "Post1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "This is placeholder text numer 2 it may be changed later.",
                            Title = "Post2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "This is placeholder text numer 3 it may be changed later.",
                            Title = "Post3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "This is placeholder text numer 4 it may be changed later.",
                            Title = "Post4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "This is placeholder text numer 5 it may be changed later.",
                            Title = "Post5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "This is placeholder text numer 6 it may be changed later.",
                            Title = "Post6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
